version: '3'

services:
  batchtransfer:
    container_name: batchtransfer1
    image: thundercoretw/batchtransfer:b5c7d4c
    hostname: batchtransfer
    volumes:
      #- ./transfer.sh:/transfer.sh
      - ./BatchTransfer:/BatchTransfer
    working_dir: /BatchTransfer
    command: ["sleep", "999999"]
    restart: always

